# Generated by Django 3.2 on 2021-05-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('options', models.CharField(max_length=10000)),
                ('answers', models.CharField(max_length=10000)),
            ],
        ),
    ]
